# Usa la imagen base oficial de Python
FROM python:3.12

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el archivo de requisitos al contenedor
COPY src/requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación al contenedor
COPY src/scrapperAPI.py .

# Expone el puerto 8000 en el contenedor
EXPOSE 8000

# Ejecuta la aplicación cuando se inicie el contenedor
CMD ["python3", "scrapperAPI.py"]
